- Gulpfile.js
- package.json
currently Gulp fails on my machine with the following error:
```
$ gulp build
[17:20:42] Using gulpfile ~/dev/yiisoft/yiiframework.com2/Gulpfile.js
[17:20:42] Starting 'clean'...
[17:20:42] Starting 'styles'...
[17:20:42] Starting 'scripts'...
[17:20:42] Starting 'fonts'...
[17:20:42] Finished 'fonts' after 1.19 ms
/home/cebe/dev/yiisoft/yiiframework.com2/node_modules/gulp-autoprefixer/node_modules/postcss/lib/lazy-result.js:152
this.processing = new Promise(function (resolve, reject) {
^
ReferenceError: Promise is not defined
at LazyResult.async (/home/cebe/dev/yiisoft/yiiframework.com2/node_modules/gulp-autoprefixer/node_modules/postcss/lib/lazy-result.js:152:31)
at LazyResult.then (/home/cebe/dev/yiisoft/yiiframework.com2/node_modules/gulp-autoprefixer/node_modules/postcss/lib/lazy-resu …
```
> Fixed Gulp compatibility issues

- views/layouts/partials/_searchForm.php
Autofocus should not be used for global search - on mobile browsers focusing input activate onscreen keyboard, so right now on large screen it happens on every page load.
> Disable autofocus in global search

- assets/src/js/search.js
- components/packagist/Package.php
- components/packagist/PackagistApi.php
- config/urls.php
- controllers/ExtensionController.php
- controllers/SearchController.php
- views/extension/_search.php
- views/extension/index.php
- views/extension/package.php
- views/extension/packageMessage.php
- views/layouts/partials/footer/_downloads.php
- #50 Url for extension as "/extensions/*"
- Fix regexp for package name, example url: https://packagist.org/packages/yixuanidea.com/yii2-artdialog
- When searching for extensions should open the first page of results
- Added an error page when the extension is not found
- Fix small bugs
- Fix style code
> Fix page extensions

- views/site/resources.php
Fix "yii powered" link on image, changed "https" to "http" as it is not working on my end at all.
> Fix yii powered link on resource page

- components/AuthHandler.php
- components/mailers/EmailVerificationMailer.php
- components/mailers/MailerInterface.php
- config/params.php
- config/urls.php
- controllers/AuthController.php
- controllers/UserController.php
- mail/profileVerifyEmail-html.php
- mail/profileVerifyEmail-text.php
- mail/signupVerifyEmail-html.php
- mail/signupVerifyEmail-text.php
- migrations/m170910_204001_email_verification.php
- models/SignupForm.php
- models/User.php
- views/user/profile.php
> #169: Implemented email verification

- controllers/NewsController.php
- controllers/WikiController.php
If `title` consists only of characters that can't be translated into the url, then will be cyclic redirect.
> Fixed cyclic redirect in wiki and news

- gulpfile.js
With this method browserSync will inject the new generated css into the page, without the need of reloading.
There are two ways to make it work:
1. Accessing via port 3000 (i.e: localhost:3000/...)
2. Changing browserSync config. Remove `proxy` and set `host: yiiframework.local` . Then when you run `gulp` a snippet of code will appear on the console. Copy this code temporary on main layout.
> Added browserSync stream

- components/Formatter.php
- env/dev/config/params-local.php
- env/prod/config/params-local.php
alternative to #288
fixes #261
Avoid the following issues:
- Blocking by Content-Security-Policy header
- HTTPs vs. HTTP mixed content problems
- content filter will only allow passing images of type gif, png,
jpg, webm and svg.
other content will be blocked.
- proxied images are not able to set cookies, i.e. not able to
track users.
URLs will be replaced as in the following example:
- Input: `http://example.com/somepath/someimage.png`
- Output: `https://user-content.yiiframework.com/img/<hash>/http/example.com/somepath/someimage.png`
`<hash>` is a value generated from the URL and a secret to avoid
abuse of the proxy server.
> Proxy external images through a content filter.

- controllers/GuideController.php
- models/Guide.php
- views/guide/error-404-guide.php
- views/guide/error-404.php
- views/guide/extension-view.php
- views/guide/partials/_guide-layout.php
- views/guide/view.php
- keep guide navigation if guide was found but section not
- suggest alternative versions and languages
- suggest a search in guide context
I got a few reports about bootstrap extension 2.2 guide URLs being broken. This version has been created by packagist but is now gone, so users get 404 errors on the latest version of the bootstrap guides.
This should now help find the correct pages:
If the guide exists in that version and language but the page does not, we keep the navigation:
> Improved 404 errors for guide pages

- components/Formatter.php
I needed details/summary to be functional in the wiki if that's okay with you.
I also noticed #409, so I went ahead and added some missing elements for tables.
> Support more tags in asMarkdown()

- config/urls.php
Noticed this error after upgrading to PHP 7.3, when visiting /wiki:
```
preg_match(): Compilation failed: invalid range in character class at offset 51
```
it seems that PCRE won't be silent anymore about those errors.
> Fix invalid range in character class

- commands/GuideController.php
Changed japanese font for PDF from 'min' to 'ipxm', since the latter produces a better rendition result.
See #142 for discussion.
> fixed japanese pdf font [ci skip]

- controllers/WikiController.php
- models/Wiki.php
- views/wiki/_form.php
Added Yii 3.0 as possible choice for the version field of a Wiki article.
Also refactored the code to use `Wiki::getYiiVersionOptions()` when a list of valid versions is required.
> Add v3.0 in wiki's yii version choice

- components/forum/DummyAdapter.php
Added this missing abstract method introduced in https://github.com/yiisoft-contrib/yiiframework.com/commit/941a945035907c4d8527fc85c8e7405dfb2dcae5
> Implement getForumUserId() in the DummyAdapter

- assets/src/scss/3-global/_navbar.scss
- views/layouts/partials/_header.php
| before | after |
|-------|-------|
| ![screen shot 2019-02-23 at 5 23 16 pm](https://user-images.githubusercontent.com/304450/53289066-4e013b80-3791-11e9-95d3-e97dd0d6c04e.png) | ![screen shot 2019-02-23 at 5 21 19 pm](https://user-images.githubusercontent.com/304450/53289072-56f20d00-3791-11e9-8dcf-e8beef29c545.png)|
+ floating sub menus:
I removed the `&helip;` so that we can handle properly down to 360px devices.
> Fix website menu on small screens

- config/console.php
Fixes the problem originally reported in #311 during docs generation.
Yii searches for bower assets under `vendor/bower/` instead of `vendor/bower-asset/`
```
./yii api "2.0" --interactive=0
Start generating API 2.0...
Searching files to process... done.
Loading apidoc data from cache... no data available.
Checking for updated files... done.
432 files to update.
Processing files... done.
Updating cross references and backlinks... done.
Rendering files: 0% (0/433) ETA: n/a   Exception 'yii\base\InvalidArgumentException' with message 'The file or directory to be published does not exist: /Users/didou/oss/yiisoft-contrib/yiiframework.com/vendor/bower/bootstrap/dist'
```
> Add @bower alias for console

- assets/src/scss/header.scss
Not perfect, but already better than what we currently have.
| Before | After |
| ------- | ------ |
| ![Screen Shot 2019-03-30 at 12 43 29 AM](https://user-images.githubusercontent.com/304450/55267826-181a1000-5285-11e9-83a0-552b9c20e3a1.png)|![Screen Shot 2019-03-30 at 12 44 24 AM](https://user-images.githubusercontent.com/304450/55267825-181a1000-5285-11e9-9cc2-541f2693fbef.png)
The changes are merely adjustments as the work conducted in #430 have already impacted this part. 
Discourse theme settings needs to be updated with the `CSS` and `Header` sections of `/admin/discourse` for both mobile & desktop.
Fixes #425
> Enhance the menu layout for forum on mobile devices

- assets/src/scss/6-elements/index/_tour.scss
> add more "air" to slider

- views/guide/index.php
This fixes a bug on the Guide index, where the search form will always use version 2.0 despite the version selected.
To reproduce this bug:
- Visit https://www.yiiframework.com/doc/guide/1.1/en
- Enter something in "Search the Guide"
- You will end up on https://www.yiiframework.com/search?language=en&version=2.0&type=guide&q=test (wrong version)
> Fix: use the correct guide version number in guide search index

- views/site/chat.php
Moving from Freenode/Fleenode/Leenode to Libera Chat.
> Update chat page with Libera Chat info and URIs

- commands/GithubProgressController.php
- components/github/GithubProgress.php
An addition to #969 / #965.
1\. This avoids unnecessary retries.
Unfortunately there are other exceptions using this class. They can have the same status code too. So the only way to distinguish it from the rest is to check the text message. The extension proxies this text from Github. If it changes over time, we'll see it in Rollbar anyway.
Also now logging exception text is not needed - if it's different error or timeout on last retry - we'll see all details in Rollbar in more visual way.
2\. Removed linebreak between properties for consistency.
> Better error handling for Github progress timeout, minor code style fix

- models/Extension.php
- views/extension/files.php
- views/extension/view.php
| Fixed issues  | #1001
I know it's not so flexible in terms of formatting, but thought that adding a separate column would be over complication for now. Can redo implementation if needed. I doubt that a suffix and formatting will change in the future though. There is always a chance, in this case a preview can be extracted or a data migration can be performed.
> Limit an extensions' tagline when importing from Packagist

- models/ChangePasswordForm.php
> Fix #460: Session / remember me is not invalidated on password change

- controllers/UserController.php
Сhanging the password or email leads to logout with warning log message: yii\web\User::renewAuthStatus - Invalid session auth key attempted for user ...
| Fixed issues  |
> Switches to a new identity when change password or email
