yiisoft-contrib/yiiframework.com

- Gulpfile.js
It is silly to create autoprefixerOptions when we don't actually use it :p
> Do use the prefixer options that we wrote

- Gulpfile.js
it will crash with a 'sourcemap not in std::in' or something..
> Can't call sourcemaps write before minifycss

- scss/4-components/_login.scss
- views/site/login.php
- views/site/signup.php
I was working on login and signup pages. @jacmoe can you check this out?
Bare in mind, this is the first time I use sass ;)
> login and signup pages

- assets/src/js/search.js
- components/Packagist.php
- config/urls.php
- controllers/ExtensionController.php
- controllers/SearchController.php
- views/extension/_search.php
- views/extension/index.php
- views/extension/package.php
- views/layouts/main.php
- views/site/partials/index/_extensions.php
- widgets/Alert.php
> Add page extensions

- assets/src/scss/5-pages/_wiki.scss
- views/site/wiki.php
#145 Wiki design page in styled and coded. If there needs something to be changed, please comment below.
> Wiki page design

- assets/src/scss/4-components/_login.scss
- models/LoginForm.php
- views/site/login.php
#165 Add "remember me" checkbox to user login
> Add "remember me" checkbox to user login

- .gitignore
- commands/SitemapController.php
- composer.json
- composer.lock
- config/console.php
- config/params.php
- config/web.php
- env/dev/config/params-local.php
- env/prod/config/params-local.php
- scripts/cron-daily.sh
#158 Add sitemap:
- api
- guide, blog
- news
- in other sections only main page
Sitemap include head /sitemap.xml and sub-files /sitemap/item_N.xml. Run generate sitemap added to cron-daily.
> Add sitemap

- assets/src/js/star.js
- assets/src/scss/4-components/star.scss
- assets/src/scss/all.scss
- config.yml
- controllers/AjaxController.php
- models/Star.php
- widgets/Star.php
- widgets/views/star.php
#166 add star button and controller actions
> Implement star/bookmark for wiki and extensions

- README.md
- commands/CronController.php
- components/contentShare/EntityInterface.php
- components/contentShare/services/BaseService.php
- components/contentShare/services/TwitterService.php
- composer.json
- composer.lock
- controllers/WikiController.php
- env/dev/config/params-local.php
- env/prod/config/params-local.php
- jobs/ContentShareJob.php
- jobs/JobException.php
- migrations/m171018_174853_content_share.php
- models/ContentShare.php
- models/ContentShareQuery.php
- models/Extension.php
- models/News.php
- models/Wiki.php
issue #231 
It is also possible to connect other services.
> Automatically publication contents (news, wiki, extension) to Twitter. 

- controllers/ExtensionController.php
- controllers/WikiController.php
> Fixes #248: New users currently see 403 when creating extension or wiki

- migrations/m180319_145940_content_share__change_type_time.php
- models/ContentShare.php
Property `created_at` is integer.
> Bug: ContentShare timestamp behavior.

- assets/src/js/star.js
- assets/src/js/voting.js
> Fixes #266: Follow button should appear only to logged in users

- assets/src/scss/1-common/_fixes.scss
- views/extension/_form.php
> Fixes #262: Fixed radio buttons at extension create page

- config/urls.php
- controllers/UserController.php
- models/ChangePasswordForm.php
- views/user/changePassword.php
- views/user/profile.php
> Fixes #286: there is no option to change password

- views/wiki/_sidebar.php
> Added All filter for Popular Tags in Wiki

- views/extension/_sidebar.php
I tried to fix it. But not sure this will work or not.
Fixes #296
> Added All filter to Popoular Tags in Extension.

- commands/RbacController.php
> Fixes #283: Fixed losing RBAC assignments

- assets/src/scss/5-pages/_index.scss
- views/wiki/partials/_versions.php
> fix #312 and #314

- assets/src/js/editor.js
- assets/src/scss/2-vendors/codemirror.scss
- config/urls.php
- controllers/SiteController.php
- views/wiki/_form.php
> Fixes #285: Added preview for markdown editors

- apidoc/ApiRenderer.php
- apidoc/ExtensionApiRenderer.php
- apidoc/views/extension-index.php
- assets/src/scss/4-components/_sectionheader.scss
- commands/ApiController.php
- commands/FakeDataController.php
- commands/GuideController.php
- components/packagist/Package.php
- config/params.php
- config/urls.php
- controllers/ApiController.php
- controllers/ExtensionController.php
- controllers/GuideController.php
- jobs/ExtensionImportJob.php
- migrations/m180403_165936_extension_version_references.php
- models/Extension.php
- models/Guide.php
- models/GuideSection.php
- views/api/partials/_versions.php
- views/api/view2x.php
- views/extension/_info.php
- views/guide/extension-index.php
- views/guide/extension-view.php
- views/guide/partials/_scrollspy.php
- views/guide/partials/_versions.php
- views/layouts/main.php
- views/layouts/partials/_sectionHeader.php
fixes #275 
---
---
---
---
open tasks:
> WIP implemented api and guide documentation for official extensions

- assets/src/scss/4-components/comments.scss
- widgets/views/comments.php
User Contributed Notes Design Issue #297
> Resolve User Contributed Notes Design Issue

- assets/src/scss/4-components/search.scss
- assets/src/scss/5-pages/_extensions.scss
- controllers/ExtensionController.php
- models/ExtensionQuery.php
- views/extension/_form.php
- views/extension/_sidebar.php
- views/extension/index-official.php
- views/extension/index.php
making them more visible. fixes #332
> added extra page for official extensions

- components/github/GithubRepoStatus.php
- config/urls.php
- controllers/StatusController.php
- views/status/index.php
> Added release statuses page

- composer.json
- composer.lock
- config/params.php
- config/web.php
- models/SignupForm.php
- views/auth/signup.php
> Added reCaptcha to signup form

- assets/src/scss/5-pages/_extensions.scss
> Fixes #364: Add max width for images in extensions

- commands/SitemapController.php
> Fixes #366: sitemap generation fails

- assets/src/js/upload.js
- assets/src/scss/4-components/_user_avatar.scss
- assets/src/scss/all.scss
- commands/ImportController.php
- composer.json
- composer.lock
- config.yml
- config/urls.php
- controllers/BaseController.php
- controllers/GuideController.php
- controllers/UserController.php
- models/User.php
- models/UserAvatarUploadForm.php
- views/user/_avatar.php
- views/user/profile.php
> Added profile picture function to profile

- assets/src/scss/6-elements/guide/_rtl.scss
- config/params.php
https://github.com/yiisoft/yii2/pull/16952#issuecomment-445826741
> WIP arabic guide

- models/Wiki.php
Category ID to Category
tagNames to Tags
> Renamed Attribute Labels

- components/github/GithubRepoStatus.php
- composer.json
- composer.lock
- controllers/StatusController.php
Switched status/index to the GraphQL API by updating `knplabs/github-api` to `^2.11`.
* We're down from 85 REST queries (approx 20 seconds) to 1 GraphQL query (2 seconds).
* Fixes `yiisoft/yii2` showing 3.0.0-alpha1 
* Uses releases to consolidate results if found
Aside from the performance optimization, this will allow you to fetch more information, like number of open issues / pull requests, etc.
Generated table:
Repository | Latest | No Release For | Status | Diff
-- | -- | -- | -- | --
yiisoft/active-record |   |   |   |  
yiisoft/cache |   |   |   |  
yiisoft/db |   |   |   |  
yiisoft/db-elasticsearch |   |   |   |  
yiisoft/db-mongodb |   |   |   |  
yiisoft/db-mssql |   |   |   |  
yiisoft/db-mysql |   |   |   |  
yiisoft/db-oracle |   |   |   |  
yiisoft/db-pgsql |   |   |   |   …
> Switch to GitHub v4 API for the StatusController

- .travis.yml
- tests/functional/ContactFormCest.php
- tests/functional/SecurityFormCest.php
> Fix travis build

- controllers/AuthController.php
- migrations/m190331_122553_add_avatar_version.php
- models/User.php
- models/UserAvatarUploadForm.php
> Fix avatar linking with forum

- composer.json
- composer.lock
Because dogfooding never hurts.
> Upgrade to yii2-debug 2.1@dev

- config/versions.php
Fixes https://forum.yiiframework.com/t/yii-1-1-21-is-released/125577/2?u=rob006
> Fix download URL for 1.1.21

- components/github/GithubRepoStatus.php
- config/urls.php
- controllers/StatusController.php
- views/status/index.php
- views/status/partials/_versions.php
- Added version selection to the status page (default to 2.0)
- Added number of open issues & pull requests for each repo
- Updated Yii 3 repositories list
> Split status page by version, add issues & pulls numbers

- models/ContactForm.php
Resolved https://github.com/yiisoft/yii2/issues/17439
> Resolved https://github.com/yiisoft/yii2/issues/17439

- assets/src/scss/header.scss
Issue [link](https://github.com/yiisoft-contrib/yiiframework.com/issues/461)
> fix dropdown & converting to a uniform font size style on 320 screen

- assets/src/scss/3-global/_footer.scss
Correct display of items on the mobile and in general on all screens
> remove footer default padding

- assets/src/scss/3-global/_content.scss
Page - https://www.yiiframework.com/doc/guide/2.0/en
Before:
After:
> guide page items fix on tablet

- assets/src/scss/2-vendors/glide.theme.scss
> white stripe fix

- assets/src/scss/5-pages/_wiki.scss
[issue](https://github.com/yiisoft-contrib/yiiframework.com/issues/472)
> fix link is out of scope

- assets/src/scss/4-components/_login.scss
[issue](https://github.com/yiisoft-contrib/yiiframework.com/issues/206)
> add indent to social login block

- assets/src/scss/5-pages/_logo.scss
> fix img on Official Logos page

- assets/src/scss/6-elements/index/_booksvideos.scss
- views/site/partials/_books.php
> ui books page update on mobile & tablet

- assets/src/scss/5-pages/_team.scss
- views/site/team.php
> update team page on mobile (ui improvements)

- assets/src/scss/4-components/_login.scss
- views/auth/partials/_githubLogin.php
> update github social icon on login page

- assets/src/scss/5-pages/_report.scss
> fix extensions block on report page

- assets/src/scss/3-global/_highlight.scss
- assets/src/scss/6-elements/guide/_blockquotes.scss
> restyle code & blockquote block on mobile

- assets/src/scss/6-elements/guide/_blockquotes.scss
> fix blockquote text link

- assets/src/scss/5-pages/_guide.scss
> fix guide view code & link wrap

- assets/src/scss/5-pages/_api.scss
> fix docs page text goes off screen

- views/guide/partials/_guide-layout.php
> update guide layout

- assets/src/scss/5-pages/_guide.scss
> fix guide text wrap

- assets/src/scss/3-global/_sidenav.scss
> add more font size to navigation

- assets/src/scss/4-components/comments.scss
> fix comment text wrap

- assets/src/scss/4-components/comments.scss
> add responsive img to comments

- assets/src/scss/5-pages/_wiki.scss
> add responsive img to wiki page

- assets/src/scss/5-pages/_guide.scss
- views/guide/extension-view.php
- views/guide/view.php
> fix prev next block on mobile & tablet

- assets/src/scss/2-vendors/custom-bootstrap/_yii-button-groups.scss
> fix version selector dropdown on mobile

- assets/src/scss/2-vendors/custom-bootstrap/_yii-button-groups.scss
> fix button group dropdown on mobile

- assets/src/scss/5-pages/_extensions.scss
> update ui extension item on mobile

- assets/src/scss/5-pages/_search.scss
> fix search results

- assets/src/scss/3-global/_navbar.scss
> fix scrolling screen appears on mobile

- assets/src/scss/4-components/_siteheader.scss
> update title on mobile

- assets/src/scss/3-global/_highlight.scss
> code goes off screen fix

- assets/src/scss/3-global/_externallinks.scss
> fix user table on mobile device

- assets/src/scss/5-pages/_halloffame.scss
> update UI "Hall of Fame" page on mobile

- views/site/report-issue.php
> update UI "report issue" page on mobile

- assets/src/scss/5-pages/_download.scss
> remove custom padding

- assets/src/scss/2-vendors/glide.theme.scss
> fix responsive image on tablet

- assets/src/scss/5-pages/_api.scss
> update title on mobile devices

- assets/src/scss/5-pages/_guide.scss
> update title & star block on mobile

- assets/src/scss/5-pages/_index.scss
- views/site/index.php
> content ui improvements

- views/site/resources.php
> resources page update

- assets/src/scss/5-pages/_search.scss
> update title and label for search results on mobile devices

- assets/src/scss/5-pages/_guide.scss
> centered items in edit box

- views/layouts/partials/footer/_supporters.php
> fix supported links

- assets/src/scss/5-pages/_report.scss
> centering content in report issue button

- assets/src/scss/5-pages/_guide.scss
> edit box block update

- views/site/download.php
> update title block on download page

- views/site/books.php
> update ui book block on mobile

- assets/src/scss/5-pages/_report.scss
- views/site/security.php
> add form indent on mobile

- assets/src/scss/3-global/_dashedheadings.scss
> update titles on mobile

- assets/src/scss/5-pages/_team.scss
- views/site/team.php
> refactor icons on team page

- widgets/views/comments.php
> update comments head for mobile

- assets/src/scss/4-components/pagination.scss
- assets/src/scss/all.scss
issue https://github.com/yiisoft-contrib/yiiframework.com/issues/586
> update pagination on mobile

- assets/src/scss/3-global/_navbar.scss
issue https://github.com/yiisoft-contrib/yiiframework.com/issues/589
> fix dropdown item color on focus

- assets/src/scss/5-pages/_team.scss
issue https://github.com/yiisoft-contrib/yiiframework.com/issues/591
> team social icons ui update

- assets/src/scss/5-pages/_resources.scss
issue https://github.com/yiisoft-contrib/yiiframework.com/issues/595
> add indent to background image

- widgets/views/versionCalendar.php
issue https://github.com/yiisoft-contrib/yiiframework.com/issues/597
> fix validation

- assets/src/js/custom.js
issue https://github.com/yiisoft-contrib/yiiframework.com/issues/603
> fix empty dropdown

- apidoc/layouts/api.php
issue https://github.com/yiisoft-contrib/yiiframework.com/issues/605
> update columns on tablet (api pages)

- assets/src/scss/3-global/_externallinks.scss
https://github.com/yiisoft-contrib/yiiframework.com/issues/607
> fix external link table on mobile

- assets/src/scss/3-global/_footer.scss
https://github.com/yiisoft-contrib/yiiframework.com/issues/624
> update footer social icons transition

- assets/src/scss/4-components/_sectionheader.scss
https://github.com/yiisoft-contrib/yiiframework.com/issues/647
> fix dropdown

- assets/src/scss/4-components/_login.scss
https://github.com/yiisoft-contrib/yiiframework.com/issues/649
> update input form color

- assets/src/scss/5-pages/_api.scss
fix issue https://github.com/yiisoft-contrib/yiiframework.com/issues/502
> fix api links

- views/site/error.php
https://github.com/yiisoft-contrib/yiiframework.com/issues/656
> update 404 page

- assets/src/scss/5-pages/_extensions.scss
https://github.com/yiisoft-contrib/yiiframework.com/issues/658
> fix sidebar menu

- assets/src/scss/4-components/_login.scss
https://github.com/yiisoft-contrib/yiiframework.com/issues/660
> update form placeholder

- assets/src/scss/5-pages/_extensions.scss
https://github.com/yiisoft-contrib/yiiframework.com/issues/662
> small ui update extension box (add indent)

- views/site/contact.php
https://github.com/yiisoft-contrib/yiiframework.com/issues/665
> update contact page

- assets/src/scss/3-global/_dashedheadings.scss
https://github.com/yiisoft-contrib/yiiframework.com/issues/667
> fix dashed heading

- assets/src/scss/5-pages/_api.scss
- assets/src/scss/5-pages/_badges.scss
- assets/src/scss/5-pages/_books.scss
- assets/src/scss/5-pages/_contribute.scss
- assets/src/scss/5-pages/_download.scss
- assets/src/scss/5-pages/_extensions.scss
- assets/src/scss/5-pages/_guide.scss
- assets/src/scss/5-pages/_halloffame.scss
https://github.com/yiisoft-contrib/yiiframework.com/issues/677
> refactor pages folder

- models/ResetPasswordForm.php
Related to https://github.com/yiisoft/yii2/pull/18540/
> Renew auth key on password reset

- views/guide/error-404-guide.php
- views/guide/partials/common/_heading.php
fix issue https://github.com/yiisoft-contrib/yiiframework.com/issues/801
> fix horizontal scroll

- assets/src/scss/5-pages/_search.scss
fix issie https://github.com/yiisoft-contrib/yiiframework.com/issues/833#issuecomment-875349361
> fix Accessibility search labels

- views/status/yii3-progress.php
fix issue https://github.com/yiisoft-contrib/yiiframework.com/issues/864
> update yii3 progress page on mobile

- config/books1.php
- config/books2.php
https://github.com/yiisoft-contrib/yiiframework.com/issues/914
> update http to https config folder

- migrations/BaseMigration.php
https://github.com/yiisoft-contrib/yiiframework.com/issues/916
> update http to https migrations folder

- models/Rating.php
https://github.com/yiisoft-contrib/yiiframework.com/issues/918
> update http to https models folder

- views/extension/_form.php
- views/layouts/partials/footer/_socialcopyright.php
- views/news/index.php
- views/site/community.php
- views/site/contribute.php
- views/site/index.php
- views/site/license.php
- views/site/logo.php
- views/site/resources.php
https://github.com/yiisoft-contrib/yiiframework.com/issues/920
> update http to https views folder

- README.md
https://github.com/yiisoft-contrib/yiiframework.com/issues/922
> update http to https README.md

- gulpfile.js
https://github.com/yiisoft-contrib/yiiframework.com/issues/924
> update http to https gulpfile

- config/books1.php
- config/books2.php
https://github.com/yiisoft-contrib/yiiframework.com/issues/926
> update yii book link

- config/books2.php
https://github.com/yiisoft-contrib/yiiframework.com/issues/928
> update packtpub link

- package.json
https://github.com/yiisoft-contrib/yiiframework.com/issues/936
> update package.json homepage link

- README.md
https://github.com/yiisoft-contrib/yiiframework.com/issues/938
> update readme homepage link

- init.bat
https://github.com/yiisoft-contrib/yiiframework.com/issues/942
> update init links

- apidoc/ExtensionApiRenderer.php
> Added missing links for viewing and editing source code

- apidoc/ExtensionApiRenderer.php
Fixes https://github.com/yiisoft/yii2-apidoc/issues/36.
> :warning: Depends on this PR - https://github.com/yiisoft/yii2-apidoc/pull/260.
> Adjust "All classes" url and "Available since version" label for type for extensions in HTML API

- yii.bat
https://github.com/yiisoft-contrib/yiiframework.com/issues/951
> update yii.bat links

- yii_test
https://github.com/yiisoft-contrib/yiiframework.com/issues/953
> update yii_test links

- yii_test.bat
https://github.com/yiisoft-contrib/yiiframework.com/issues/955
> update yii_test.bat links

- config/donation-services.php
> Fix opencollective link

- commands/GithubProgressController.php
- components/github/GithubProgress.php
> Minor naming and log messages fixes

- Makefile
| Is bugfix?    | ❌
| Fixed issues  |
> Improve extensions' readability in Makefile

- views/layouts/fullpage.php
- views/layouts/main.php
resolve https://github.com/yiisoft-contrib/yiiframework.com/issues/1016
> remove support for older browsers

- components/github/GithubProgress.php
- views/github-progress/yii3-progress.php
> Remove internal packages from progress, fix link

- views/site/contribute.php
| Fixed issues  | https://github.com/yiisoft-contrib/yiiframework.com/issues/1031
> fix broken link

- views/github-progress/yii3-progress.php
- views/site/contribute.php
- views/site/partials/index/_jumbo.php
> Fix donate links

- models/NewsQuery.php
| Is bugfix?    | ❌
| Fixed issues  | #1029
> Fix #1029: add id to news sorting

- views/site/chat.php
| Is bugfix?    | ❌
| Fixed issues  | 
Added international telegram channel to list of communication channels.
Not tested locally.
> Add telegram channel

- views/site/donate.php
| Is bugfix?    |❌
| New feature?  |❌
| Breaks BC?    |❌
| Fixed issues  |
> Add Tidelift to donation page

- views/github-progress/index.php
> Fix condition for unreleased package row

- README.md
- composer.json
- composer.lock
- models/Extension.php
> Fix: Packagist.org v1 metadata deprecated
